---
title: "first glance"
author: "m"
date: "October 17, 2018"
output: 
  html_document
---

```{r echo=FALSE, results='asis'}
source(file_in("./R/rmd_prep.R"))
```


```{r, echo=FALSE}
suppressMessages(source(file_in("./R/libs.R")))

# "Self-invalidation"-issue
#source(file_in("./R/funs.R"))

train <- readd(d)$train
loadd(d_cor)
```


# cor

```{r, fig.width=20, fig.height=20, echo=FALSE}
corrr::network_plot(d_cor)

d_cor %>% 
  corrr::as_matrix() %>% 
  corrplot::corrplot(method = "ellipse", order = "hclust")#, addrect = integer
```

# cross_plot

```{r, echo=FALSE}
funModeling::cross_plot(train, input = c("spotfibercountch3"), target = "y")
```

# simple tree

```{r, fig.width=20, fig.height=20, echo=FALSE}
var_char <- train %>% dplyr::select_if(is.character) %>% names()

for (depth in 1:4) {
  partykit::ctree(y ~ ., data = dplyr::select(train, -dplyr::one_of(var_char)), maxdepth = depth) %>% 
  plot
}

partykit::ctree(y ~ ., data = dplyr::select(train, -dplyr::one_of(var_char))) %>% 
  plot
```

# sessionInfo

```{r, echo=FALSE}
sessionInfo()
```