library(kernlab)
library(parsnip)
library(e1071)
library(corrr)
library(corrplot)
library(partykit)
library(caret)
library(embed)
library(rsample)
library(recipes)
library(knitr)
library(dplyr)
library(tidyr)
library(readr)
library(futile.logger)
library(glue)
library(vtreat)
library(funModeling)
library(drake)
flog.info("libs loaded")


pkgconfig::set_config("drake::strings_in_dots" = "literals")